spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # Redis 비활성화
  redis:
    enabled: false

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ASDF!@#$%^&*()

h2:
  console:
    enabled: true
    settings:
      web-allow-others: true
    path: /h2-console

datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  driver-class-name: org.h2.Driver
