server:
  port: 8081

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  jpa:
    hibernate:
      #      ddl-auto: none
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/demo
    username: root
    password: gw2157214
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ASDF!@#$%^&*()
